# Generated by Django 4.1.5 on 2023-02-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userdetail_delete_usergeodetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdetail",
            old_name="holiday_name",
            new_name="holiday",
        ),
    ]
