# Generated by Django 4.1.5 on 2023-02-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_holiday_name_userdetail_holiday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
