# Generated by Django 4.1.5 on 2023-02-02 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_posts_unlikes_alter_posts_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="blogpost_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
